package com.sample

import com.sample.model.Item;
import com.sample.model.Store;
import com.sample.model.Client;

global javax.swing.JTextField QUANTITY
global javax.swing.JTextField PURCHASE_VALUE
global javax.swing.JList STORE_LIST
global javax.swing.JList CART_LIST

rule "Buy Item"
no-loop true
    salience 100
when
    $client : Client()
    $item : Item()
    $store : Store()
then
    $client.addToCart($item);
    $store.removeItem($item);
    STORE_LIST.setListData($store.getItems().toArray());
    CART_LIST.setListData($client.getCart().toArray());
    PURCHASE_VALUE.setText("" + $client.getPurchaseValue());
    QUANTITY.setText("" + $client.getTotalCartItems());
    System.out.println($item.getName() + " added to cart!");
    System.out.println("Purchase value : " + $client.getPurchaseValue() + " Total items : " + $client.getTotalCartItems());
    update($client)
    update($store)
end
