package com.sample

import com.sample.model.Client;
import com.sample.Constants.Gender;
import com.sample.Constants.MaritalStatus
import javax.swing.JOptionPane
import com.sample.model.Item
import javax.swing.DefaultListModel;
import java.util.List;
import javax.swing.JList;
import com.sample.model.Store

/**
a) O cliente deseja comprar um certo item (correspondente ao seu sexo);

b) Caso o cliente possua filhos, o sistema deve depois recomendar a compra de uma t-shirt de criança com
o dizer “A minha mama é a melhor” ou o “O meu papa é o melhor”, dependendo do sexo do cliente
(esta recomendação só deverá ser feita uma vez por compra, caso já tenha sido feita, deverá ser feita a
recomendação da alínea c) ou d), consoante o cliente seja ou não casado);

c) Caso o cliente não possua filhos, mas seja casado, o sistema deve recomendar um item com a mesma
descrição ao escolhido, mas para o sexo oposto;

d) Caso o cliente não possua filhos nem seja casado, o sistema deve recomendar o item “complementar”;

e) Sempre que um item é adicionado, o sistema deve apresentar o valor corrente da compra.

f) Ao terminar a compra, deve ser apresentada uma mensagem com a quantidade de itens comprados e o
valor final.
**/

/**
* Recommend an item, returns boolean, true if user accepts recommendation
**/
function boolean recommendItem(Item item) {
    int dialogResult = JOptionPane.showConfirmDialog (null, item.toString(), "Would You Like to Accept suggestion?", JOptionPane.YES_NO_OPTION);

    return (dialogResult == JOptionPane.YES_OPTION);
}

rule "Client is male and has children"
    no-loop true
    salience 90
    when
        $client : Client(gender == Gender.MALE, hasChildren == true)
        $store : Store()
        $recommendation : Item ( name == "TSHIRT - O meu papa e o melhor" ) from $store.getItems()
        not Item ( name == "TSHIRT - O meu papa e o melhor" ) from $client.getRecommendations()
        $item : Item( !isRecommendation() )
    then
        System.out.println("Rule 1");
        $client.addRecommendation($recommendation);
        if (recommendItem($recommendation)) {
            $recommendation.setRecommendation(true);
            insert($recommendation);
        }

        retract($item)
        update($client)
end

rule "Client is female and has children"
    no-loop true
    salience 80
    when
        $client : Client( gender == Gender.FEMALE, hasChildren == true )
        $store : Store()
        $recommendation : Item ( name == "TSHIRT - A minha mama e a melhor" ) from $store.getItems()
        not Item ( name == "TSHIRT - A minha mama é a melhor" ) from $client.getRecommendations()
        $item : Item( !isRecommendation() )
    then
        System.out.println("Rule 2");
        $client.addRecommendation($recommendation);
        if (recommendItem($recommendation)) {
            $recommendation.setRecommendation(true);
            insert($recommendation);
        }

        retract($item)
        update($client)
end

rule "Client is male, married and doesn't has children"
    no-loop true
    salience 70
    when
        $client : Client( gender == Gender.MALE, maritalStatus == MaritalStatus.MARRIED, hasChildren == false )
        $store : Store()
        $item : Item( !isRecommendation() )
        $recommendation : Item ( name == $item.name, gender == Gender.FEMALE ) from $store.getItems()
    then
        System.out.println("Rule 3");
        $client.addRecommendation($recommendation);
        if (recommendItem($recommendation)) {
            $recommendation.setRecommendation(true);
            insert($recommendation);
        }

        retract($item)
        update($client)
end

rule "Client is female, married and doesn't has children"
    no-loop true
    salience 60
    when
        $client : Client( gender == Gender.FEMALE, maritalStatus == MaritalStatus.MARRIED, hasChildren == false )
        $store : Store()
        $item : Item( !isRecommendation() )
        $recommendation : Item ( name == $item.name, gender == Gender.MALE ) from $store.getItems()
    then
        System.out.println("Rule 4");
        $client.addRecommendation($recommendation);
        if (recommendItem($recommendation)) {
            $recommendation.setRecommendation(true);
            insert($recommendation);
        }

        retract($item)
        update($client)
end

rule "Client is male, married and has children"
    no-loop true
    salience 50
    when
        $client : Client( gender == Gender.MALE, maritalStatus == MaritalStatus.MARRIED, hasChildren == true )
        $store : Store()
        $item : Item( !isRecommendation() )
        $recommendation : Item ( name == $item.name, gender == Gender.FEMALE ) from $store.getItems()
    then
        System.out.println("Rule 5");
        $client.addRecommendation($recommendation);
        if (recommendItem($recommendation)) {
            $recommendation.setRecommendation(true);
            insert($recommendation);
        }

        retract($item)
        update($client)
end

rule "Client is female, married and has children"
    no-loop true
    salience 40
    when
        $client : Client( gender == Gender.FEMALE, maritalStatus == MaritalStatus.MARRIED, hasChildren == true )
        $store : Store()
        $item : Item( !isRecommendation() )
        $recommendation : Item ( name == $item.name, gender == Gender.MALE ) from $store.getItems()
    then
        System.out.println("Rule 6");
        $client.addRecommendation($recommendation);
        if (recommendItem($recommendation)) {
            $recommendation.setRecommendation(true);
            insert($recommendation);
        }

        retract($item)
        update($client)
end

rule "Client is single and doesn't has children"
    no-loop true
    salience 30
    when
        $client : Client( maritalStatus == MaritalStatus.SINGLE, hasChildren == false )
        $store : Store()
        $item : Item( complementaryItem != null, !isRecommendation() )
    then
        System.out.println("Rule 7");
        $client.addRecommendation($item.getComplementaryItem());

        if (recommendItem($item.getComplementaryItem())) {
            $item.getComplementaryItem().setRecommendation(true);
            insert($item.getComplementaryItem());
        }

        retract($item)
        update($client)
end

rule "Client is single and has children"
    no-loop true
    salience 20
    when
        $client : Client( maritalStatus == MaritalStatus.SINGLE, hasChildren == true )
        $store : Store()
        $item : Item( complementaryItem != null, !isRecommendation() )
    then
        System.out.println("Rule 8");
        $client.addRecommendation($item.getComplementaryItem());

        if (recommendItem($item.getComplementaryItem())) {
            $item.getComplementaryItem().setRecommendation(true);
            insert($item.getComplementaryItem());
        }

        retract($item)
        update($client)
end

rule "Remove item"
    no-loop true
    salience 10
	when
		$item : Item();
	then
		retract($item);
end